### PR TITLE
Complete Revision on GET Todo Items API Call

### PR DESCRIPTION
**Pull request by Sanlung**
**Rework of `getAllTodos` controller function to GET only items belonging to a particular todo list**

This revision has the following changes:
1. Rework of the `/server/controller/todos.js`, `/server/controllers/todos.js`, `/server/__test__/todos.js` and `/server/swagger.yaml` to make back end API call to GET a listfull of todo items at a time.
2. Edited the back end files/modules to include the changes discussed in comments re PR#6.
3. The API route now for fetching todo items is `${BASE_URL}/api/v1/todos/?list=${list_id}`
4. The current logic and routing with query string(s) in `/server/controllers/todos.js`'s `getTodos` function can be edited to include pagination by simply including `page` and `limit` query strings and associated logic.
5. The tests suites in `/server/__test__/todos.js` and the Swagger docs include changes made in this revision, and are tested to work.

**Other proposals set forth in issue#10 are not implemented in this revision**

**All the front-end code (i.e., in `/src/` is removed to provide for the discretion of the front end team**

### CODE REVIEW

**Comment by tarikutk** [comment]
@Sanlung , this Pr has a conflict.

**Comment by Sanlung** [comment]
@tarikutk All intervening changes made by Sherose up to PR#16 (which literally removed all back-end code because reversion of PR#6 and PR#9 per PR#14 and PR#15 literally removed all back end code) is now incorporated in the changes proposed in this PR.

Resolving the merge was quite involved, but nothing that could not be handled.

**Comment by tarikutk** [comment]
Hi @Sanlung , currently when I run the pr it is failing, the app is showing empty place. in app.js lets move the header above routes. 
```
<BrowserRouter>
<Header />
<Routes>
```

**Comment by tarikutk** [comment]
lets also update index.js threse way. 
```
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

const container = document.getElementById('root');
const root = ReactDOM.createRoot(container);
```

**Review by tarikutk — APPROVED** [review]
working Good.

**Pull request merged**
