### PR TITLE
Edit list item

### PR DESCRIPTION
**Pull request by essbee23**
Edit function does not work. 

Pushing for review, intend to continue working on it:

> two input fields open when handleEditClick

> focus moves to original input field

> Edit input no longer teleports but also does not replace text. Can cancel.

### CODE REVIEW

**Review by tarikutk — CHANGES_REQUESTED** [review]

**Comment by tarikutk** [comment]
Edit todo list not working.

**Comment by tarikutk** [comment]
I think this can be a resource to get some idea. it has edit/delete/checkbox feature like we want it. [https://www.youtube.com/watch?v=dD0MdMRVHoo](https://www.youtube.com/watch?v=dD0MdMRVHoo)

**Review by Sanlung — CHANGES_REQUESTED** [review]
Hello, Sherose. I apologize for the tardiness in reviewing and offering comments concerning this PR. It came to light after writing a few line comments about your code that the dev code base now has code and project directory organization that not only are approved changes, but will require you to pull from team3 dev `main` and accept into your `edit-list-item` local branch by a merge in any event before your proposal will be approved.

It's rather involved to explain what all this means as a matter of workflow; it's easier to discuss synchronously. So please ring me on Slack if you want to know the details or have a discussion about this branch.

And to cut straight into the point, please run the commands that I've posted on the team Slack channel to pull team3-dev `main` branch to you local `main` and either accept the approved changes into this `edit-list-item` branch (which will require you discard some changes having been made locally), or check out a new branch with an appropriate name for what you would do in the branch (see below suggestion) before revising code. Then I'd suggest you take a look to understand the current project state and why things are what they are, and, preferably in a branch not `edit-list-item`, work on the following increment:
1. Remove `useSemiPersistentState` form `/src/App.js` and import `useSessionPersistentState` from `/src/persisState.js` for any storage needs.
2. Edit the name and content of `/src/components/form/AddTodoForm.js` so it can be reused without confusion as to the variable and function names' appropriateness.
3. import `useSessionPersistentState` and `AddTodoForm` in the `App` and `ListPance` components and run the app to make sure your revisions did not break the app.
You may push the new branch for a PR (as this is about the size of increments suitable for a PR), or if you've merged approved changes into `edit-list-item`, you may then continue to work on the edit function for a bigger increment of work.

This branch will not be merged before you accept the approved changes in project `main` anyway. We should save review for the revision of this or a new branch.

**Comment by essbee23** [comment]
Canceled due to stalled progress and predicted backend conflicts. Will return ticket to Project board.

**Pull request closed without merging**
